Feat: Project Euler Problem 7
TheAlgorithms/Ruby pull request #202
Opened 2023-02-19 10:30 UTC by domix80

Add resolution for Euler Problem 007

2023-02-21 17:20 UTC, domix80 commented
@aparibocci, Could you please review it?

2023-02-23 06:22 UTC, domix80 commented
@StepfenShawn - May I ask you to review and eventually merge the code?

2023-02-23 14:54 UTC, StepfenShawn requested changes

2023-02-23 14:54 UTC, StepfenShawn commented on project_euler/problem_007/sol1.rb
> +#Project Euler Problem 7: #https://projecteuler.net/problem=7
```suggestion
#Project Euler Problem 7:  https://projecteuler.net/problem=7
```

2023-02-23 14:54 UTC, StepfenShawn commented on project_euler/problem_007/sol1.rb
> +#By listing the first six prime numbers: 2, 3, 5, 7, 11, #and 13, we
```suggestion
#By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we
```

2023-02-23 15:07 UTC, StepfenShawn approved these changes
thanks!

2023-02-23 15:08 UTC, merged