Feat: Project Euler Problem 10
TheAlgorithms/Ruby pull request #203
Opened 2023-02-19 10:48 UTC by domix80

Adding resolution for Euler Problem 10

2023-02-21 17:20 UTC, domix80 commented
@aparibocci, Could you please review it?

2023-02-23 06:22 UTC, domix80 commented
@StepfenShawn - May I ask you to review and eventually merge the code?

2023-02-23 14:52 UTC, StepfenShawn requested changes
A few changes about comments.

2023-02-23 14:52 UTC, StepfenShawn commented on project_euler/problem_010/sol1.rb
> +#References: - https://en.wikipedia.org/wiki/Prime_number
```suggestion
#References:  https://en.wikipedia.org/wiki/Prime_number
```

2023-02-23 14:52 UTC, StepfenShawn commented on project_euler/problem_010/sol1.rb
> +#Project Euler Problem 10: #https://projecteuler.net/problem=10
```suggestion
#Project Euler Problem 10:  https://projecteuler.net/problem=10
```

2023-02-23 15:09 UTC, merged