Feat: Project Euler Problem 14
TheAlgorithms/Ruby pull request #205
Opened 2023-02-19 13:06 UTC by domix80

Adding the resolution for Euler Problem 14: Longest Collatz sequence

2023-02-21 17:21 UTC, domix80 commented
@aparibocci, Could you please review it?

2023-02-23 06:23 UTC, domix80 commented
@StepfenShawn - May I ask you to review and eventually merge the code?

2023-02-23 14:57 UTC, StepfenShawn requested changes
Please don't update the `Directory.md `. It's updated automatically.

2023-02-23 14:57 UTC, StepfenShawn requested changes

2023-02-23 14:57 UTC, StepfenShawn commented on project_euler/problem_014/sol1.rb
> +
```suggestion
```

2023-02-23 16:14 UTC, domix80 commented
Hi @StepfenShawn ,

Thanks for the review.
I have restored director.md file

Br,
Domenico

2023-02-23 23:08 UTC, StepfenShawn approved these changes

2023-02-23 23:09 UTC, merged